export const vehicles = {
  categories: [
    { label: "Select Category", value: "" },
    { label: "Sedan", value: "sedan" },
    { label: "SUV", value: "suv" },
    { label: "Truck", value: "truck" },
    { label: "Van", value: "van" },
  ],
  brands: [
    { label: "Select Brand", value: "" },
    { label: "Toyota", value: "toyota" },
    { label: "Honda", value: "honda" },
    { label: "Ford", value: "ford" },
    { label: "Chevrolet", value: "chevrolet" },
  ],
  models: [
    { label: "Select Model", value: "" },
    { label: "Camry", value: "camry" },
    { label: "Corolla", value: "corolla" },
    { label: "Civic", value: "civic" },
    { label: "Accord", value: "accord" },
    { label: "F-150", value: "f150" },
    { label: "Silverado", value: "silverado" },
    { label: "Sierra", value: "sierra" },
    { label: "Odyssey", value: "odyssey" },
    { label: "Sienna", value: "sienna" },
    { label: "Pacifica", value: "pacifica" },
  ],
  colors: [
    { label: "Select Color", value: "" },
    { label: "Red", value: "red" },
    { label: "Blue", value: "blue" },
    { label: "Black", value: "black" },
    { label: "White", value: "white" },
    { label: "Silver", value: "silver" },
    { label: "Gray", value: "gray" },
  ],
  plateNumbers: [
    { label: "Select Plate Number", value: "" },
    { label: "ABC123", value: "abc123" },
    { label: "DEF456", value: "def456" },
    { label: "GHI789", value: "ghi789" },
    { label: "JKL012", value: "jkl012" },
  ],
};
